### ISSUE TITLE
Clicking 'Start Game' displays blank screen

### ISSUE THREAD

**Issue by BrettonMcCann** [ozboware/wordled#11]
Opening index.html with chrome displays the first screen fine. The options (help, word size, etc.) all seem to work as per the demo. But when I click 'Start Game', just goes to an screen with just two vertical lines.

I'm new to GitHub, so not sure if this is an appropriate forum for this type of question. Also, just trying to learn javascript - so I am probably missing something obvious. Thanks for your help.

**Comment by milsaware** [comment]
I've fixed the bug so it works serverless. Redownload and try again, it should work fine now.

**Comment by BrettonMcCann** [comment]
Works fine now, thanks!


Bretton McCann, P.Eng. (Retired & Travelling)
[image: Logo] <http://www.brettonmccann.ca>
T: +61 490 781 563
Frankston South, Victoria, Australia
***@***.***

www.brettonmccann.ca
[image: Facebook icon] <https://www.facebook.com/bret.mccann.73>  [image:
Twitter icon] <https://twitter.com/brettonmccann?lang=en>  [image:
Instagram icon] <http://www.brettonmccann.ca/>
