### ISSUE TITLE
Wrong color keyboard keys

### ISSUE THREAD

**Issue by Monty** [ozboware/wordled#9]
When a letter is in the wrong position, the game board correctly turns that letter gold.

However, the keyboard key turns green, not gold as it does in other implementations

<img width="295" alt="Screen Shot 2022-02-10 at 11 39 37 PM" src="https://user-images.githubusercontent.com/12963/153553684-cc6bb465-8a47-4359-9cd8-fcefd4ea752f.png">

**Comment by milsaware** [comment]
That's not wrong. It's by design. There are numerous words where letters appear more than once. It seems senseless to update the keyboard with 3 different colours when the two suffice.

**Comment by Monty** [comment]
While I prefer the wordle way, where keyboard keys don't turn green until their letter has at least one correct position,
I understand your reasoning. Your choice is fine. I can still tell by looking at the blocks. 

Looks like more work than I would attempt in any case.
